version: '3'
services:
  app:
    volumes:
      - .:/workspace:cached
    build:
      context: .
      target: app
    ports:
      - 8080:80
  db:
    image: docker.io/library/mysql:5
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root

volumes:
  mysql-data: